name: env_rain
channels:
  - defaults
  - conda-forge
dependencies:
  - python>3.9
  - geopandas=0.14
  - matplotlib=3.8
  - numpy=1.24.4
  - pandas=2.2
  - requests=2.31
  - seaborn=0.13
  - bs4=4.12
  - scipy=1.12
platforms:
  - win-64
